version: "3.9"

services:
    backend.mysql:
        image: mysql:latest
        ports:
            - 3307:3306
        volumes:
            # - /var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=jk
            - TZ=America/Argentina/Mendoza
        networks:
            - backend

    back.app:
        build: 
            context: .
        depends_on:
            - backend.mysql
        environment:
            - DATABASE_NAME=jk
            - DATABASE_USERNAME=root
            - DATABASE_PASSWORD=root
            - DATABASE_HOST=backend.mysql
        ports:
            - "5000:5000"
        restart: always
        networks:
            - backend

volumes:
    backend.mysql:
    back.app:

networks:
    backend: